name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun i --frozen-lockfile
      - run: bun run prepare
      - run: bun run start &> $GITHUB_STEP_SUMMARY
        shell: bash
      - run: bun run build
